name: submit_to_app_platform
on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  submit_to_app_platform:
    runs-on: macos-11.0
    steps:
    - name: Set up repository
      uses: actions/checkout@v2
    - name: Setup ssh if needed
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_13.2.app/Contents/Developer'
    - name: Setup Gems cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Setup flutter cache
      uses: actions/cache@v1
      with:
        path: /Users/runner/hostedtoolcache/flutter
        key: ${{runner.OS}}-flutter-install-cache
    # Correspondence of error that appears in setup-ruby
    # When executing Action, the error message was displayed to execute
    - name: Setup gem
      run: bundle lock --add-platform x86_64-darwin-19
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.4 # Not needed with a .ruby-version file
        bundler-cache: true
    # android is not supported now
    # - name: Set up java
    #   uses: actions/setup-java@v1
    #   with:
    #     java-version: "12.x"
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: "2.2.3"
    - name: Fetch flutter pub
      run: flutter pub get
    - name: Flutter test
      run: flutter test
    - name: Build ipa and submit it to AppStoreConnect
      run: ./scripts/CI/submit_app_to_app_platform.sh.sh
